# This is a basic workflow to help you get started with Actions

name: Auto Hexo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ timescapes_source ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2.1.4
      
      - name: Checkout source
        uses: actions/checkout@v2.3.4
        with: 
          ref: timescapes_source
      
      - name: Setup Build Environment
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'Gingko'
          git config --global user.email 'cbg0202@gmail.com'
          npm i -g hexo-cli
          npm i
      
      - name: Deploy
        run: |
          hexo generate && hexo deploy
